In [140]:
#https://www.kaggle.com/code/kaustubhshirpurkar/exploring-titanic-data-using-pandas-dataframes
#check previous page

import pandas as pd
import numpy as np

train = pd.read_csv('data/train.csv')
test = pd.read_csv('data/test.csv')


In [141]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   PassengerId   8693 non-null   object 
 1   HomePlanet    8492 non-null   object 
 2   CryoSleep     8476 non-null   object 
 3   Cabin         8494 non-null   object 
 4   Destination   8511 non-null   object 
 5   Age           8514 non-null   float64
 6   VIP           8490 non-null   object 
 7   RoomService   8512 non-null   float64
 8   FoodCourt     8510 non-null   float64
 9   ShoppingMall  8485 non-null   float64
 10  Spa           8510 non-null   float64
 11  VRDeck        8505 non-null   float64
 12  Name          8493 non-null   object 
 13  Transported   8693 non-null   bool   
dtypes: bool(1), float64(6), object(7)
memory usage: 891.5+ KB


In [142]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4277 entries, 0 to 4276
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   PassengerId   4277 non-null   object 
 1   HomePlanet    4190 non-null   object 
 2   CryoSleep     4184 non-null   object 
 3   Cabin         4177 non-null   object 
 4   Destination   4185 non-null   object 
 5   Age           4186 non-null   float64
 6   VIP           4184 non-null   object 
 7   RoomService   4195 non-null   float64
 8   FoodCourt     4171 non-null   float64
 9   ShoppingMall  4179 non-null   float64
 10  Spa           4176 non-null   float64
 11  VRDeck        4197 non-null   float64
 12  Name          4183 non-null   object 
dtypes: float64(6), object(7)
memory usage: 434.5+ KB


In [143]:
train.isnull().sum()

PassengerId       0
HomePlanet      201
CryoSleep       217
Cabin           199
Destination     182
Age             179
VIP             203
RoomService     181
FoodCourt       183
ShoppingMall    208
Spa             183
VRDeck          188
Name            200
Transported       0
dtype: int64

In [144]:
test.isnull().sum()

PassengerId       0
HomePlanet       87
CryoSleep        93
Cabin           100
Destination      92
Age              91
VIP              93
RoomService      82
FoodCourt       106
ShoppingMall     98
Spa             101
VRDeck           80
Name             94
dtype: int64

In [145]:
cols=train.columns

for lab in cols :
    print(lab)
    print(train[lab].unique())

PassengerId
['0001_01' '0002_01' '0003_01' ... '9279_01' '9280_01' '9280_02']
HomePlanet
['Europa' 'Earth' 'Mars' nan]
CryoSleep
[False True nan]
Cabin
['B/0/P' 'F/0/S' 'A/0/S' ... 'G/1499/S' 'G/1500/S' 'E/608/S']
Destination
['TRAPPIST-1e' 'PSO J318.5-22' '55 Cancri e' nan]
Age
[39. 24. 58. 33. 16. 44. 26. 28. 35. 14. 34. 45. 32. 48. 31. 27.  0.  1.
 49. 29. 10.  7. 21. 62. 15. 43. 47.  2. 20. 23. 30. 17. 55.  4. 19. 56.
 nan 25. 38. 36. 22. 18. 42. 37. 13.  8. 40.  3. 54.  9.  6. 64. 67. 61.
 50. 41. 57. 11. 52. 51. 46. 60. 63. 59.  5. 79. 68. 74. 12. 53. 65. 71.
 75. 70. 76. 78. 73. 66. 69. 72. 77.]
VIP
[False True nan]
RoomService
[   0.  109.   43. ... 1569. 8586.  745.]
FoodCourt
[   0.    9. 3576. ... 3208. 6819. 4688.]
ShoppingMall
[   0.   25.  371. ... 1085.  510. 1872.]
Spa
[   0.  549. 6715. ... 2868. 1107. 1643.]
VRDeck
[   0.   44.   49. ... 1164.  971. 3235.]
Name
['Maham Ofracculy' 'Juanna Vines' 'Altark Susent' ... 'Fayey Connon'
 'Celeon Hontichre' 'Propsh Hontichre']

In [146]:
numbers_train = train.select_dtypes(np.number)
bool_train = train.select_dtypes(np.bool)
cad_train = train.select_dtypes(exclude=[np.number])

print(numbers_train.columns)
print(cad_train.columns)
print(bool_train.columns)
numbers_test = test.select_dtypes(np.number)
cad_test = test.select_dtypes(exclude=[np.number])
print(numbers_test.columns)
print(cad_test.columns)


Index(['Age', 'RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck'], dtype='object')
Index(['PassengerId', 'HomePlanet', 'CryoSleep', 'Cabin', 'Destination', 'VIP',
       'Name', 'Transported'],
      dtype='object')
Index(['Transported'], dtype='object')
Index(['Age', 'RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck'], dtype='object')
Index(['PassengerId', 'HomePlanet', 'CryoSleep', 'Cabin', 'Destination', 'VIP',
       'Name'],
      dtype='object')


In [147]:
numbers_train = train.select_dtypes(np.number)
object_train = train.select_dtypes(exclude=[np.number]) #bool and strings

for numbers in numbers_train:
    train.loc[:,numbers] = train.loc[:,numbers].fillna(train.loc[:,numbers].median())
            
for obj in object_train:
    train.loc[:,obj] = train.loc[:,obj].fillna(train.loc[:,obj].mode()[0])

numbers_test = test.select_dtypes(np.number)
object_test = test.select_dtypes(exclude=[np.number]) #bool and strings
    
#fill nans with moda and median TRAIN
for numbers in numbers_test:
    test.loc[:,numbers] = test.loc[:,numbers].fillna(test.loc[:,numbers].median())

for obj in object_test:
    test.loc[:,obj] = test.loc[:,obj].fillna(test.loc[:,obj].mode()[0])
            
for lab in cols :
    print(lab)
    print(len(train[lab].unique()))

print("check nulls")
print(train.isnull().sum())
print(test.isnull().sum())

PassengerId
8693
HomePlanet
3
CryoSleep
2
Cabin
6560
Destination
3
Age
80
VIP
2
RoomService
1273
FoodCourt
1507
ShoppingMall
1115
Spa
1327
VRDeck
1306
Name
8473
Transported
2
check nulls
PassengerId     0
HomePlanet      0
CryoSleep       0
Cabin           0
Destination     0
Age             0
VIP             0
RoomService     0
FoodCourt       0
ShoppingMall    0
Spa             0
VRDeck          0
Name            0
Transported     0
dtype: int64
PassengerId     0
HomePlanet      0
CryoSleep       0
Cabin           0
Destination     0
Age             0
VIP             0
RoomService     0
FoodCourt       0
ShoppingMall    0
Spa             0
VRDeck          0
Name            0
dtype: int64


In [148]:
train['AgeBand'] = pd.qcut(train['Age'],q=3)
print(train[['AgeBand', 'Transported']].groupby(['AgeBand'], as_index=False).mean().sort_values(by='AgeBand', ascending=True))

print(len(train[train['Age']<22]))
print(len(train[ (train['Age']>=22 ) & (train['Age']<33)]))
print(len(train[train['Age']>33]))

train['RoomServicBand'] = pd.qcut(train['RoomService'],q=3,duplicates='drop')
print(train[['RoomServicBand', 'Transported']].groupby(['RoomServicBand'], as_index=False).mean().sort_values(by='RoomServicBand', ascending=True))
print(len(train[train['RoomService']<1.0]))
print(len(train[train['RoomService']>=1.0]))

train['FoodCourtBand'] = pd.qcut(train['FoodCourt'],q=3,duplicates='drop')
print(train[['FoodCourtBand', 'Transported']].groupby(['FoodCourtBand'], as_index=False).mean().sort_values(by='FoodCourtBand', ascending=True))

print(len(train[train['FoodCourt']< 2.0]))
print(len(train[train['FoodCourt']>= 2.0]))

train['ShoppingMallBand'] = pd.qcut(train['ShoppingMall'],q=3,duplicates='drop')
print(train[['ShoppingMallBand', 'Transported']].groupby(['ShoppingMallBand'], as_index=False).mean().sort_values(by='ShoppingMallBand', ascending=True))

print(len(train[train['ShoppingMall']< 0.667]))
print(len(train[train['ShoppingMall']>= 0.667]))

train['SpaBand'] = pd.qcut(train['Spa'],q=3,duplicates='drop')
print(train[['SpaBand', 'Transported']].groupby(['SpaBand'], as_index=False).mean().sort_values(by='SpaBand', ascending=True))

print(len(train[train['Spa']< 3]))
print(len(train[train['Spa']>= 3]))

train['VRDeckBand'] = pd.qcut(train['VRDeck'],q=3,duplicates='drop')
print(train[['VRDeckBand', 'Transported']].groupby(['VRDeckBand'], as_index=False).mean().sort_values(by='VRDeckBand', ascending=True))

print(len(train[train['ShoppingMall']< 1]))
print(len(train[train['ShoppingMall']>= 1]))



          AgeBand  Transported
0  (-0.001, 22.0]     0.545275
1    (22.0, 33.0]     0.473088
2    (33.0, 79.0]     0.489407
2746
2937
2832
   RoomServicBand  Transported
0   (-0.001, 1.0]     0.622128
1  (1.0, 14327.0]     0.256565
5758
2935
    FoodCourtBand  Transported
0   (-0.001, 2.0]     0.577187
1  (2.0, 29813.0]     0.353825
5755
2938
   ShoppingMallBand  Transported
0   (-0.001, 0.667]     0.596894
1  (0.667, 23492.0]     0.317115
5795
2898
          SpaBand  Transported
0   (-0.001, 3.0]     0.622440
1  (3.0, 22408.0]     0.264053
5758
2935
       VRDeckBand  Transported
0   (-0.001, 1.0]     0.617657
1  (1.0, 24133.0]     0.272379
5795
2898


In [149]:
#print(pd.crosstab(train['CryoSleep'], train['Transported']))

print(train[['CryoSleep', 'Transported']].groupby(['CryoSleep'], as_index=False).mean())

train.loc[train['Age']<0,'Age'] = 0
train.loc[ (train['Age']>=0) & (train['Age']<=22) ,'Age'] = 1
train.loc[ (train['Age']>22) & (train['Age']<=33) ,'Age'] = 2
train.loc[train['Age']>33,'Age'] = 3
train['Age'] = train['Age'].astype(int)
    
print(train[['Age', 'Transported']].groupby(['Age'], as_index=False).mean())

#erase transported column
train_aux = train.copy()
train_aux  = train_aux.drop(['Transported'], axis=1)

#join all data
result = pd.concat([train_aux,test])
print(result['RoomService'].mean())
train.loc[train['RoomService']<result['RoomService'].mean(),'RoomService'] = 0
train.loc[ (train['RoomService']>=result['RoomService'].mean()) ,'RoomService'] = 1
train['RoomService'] = train['RoomService'].astype(int)

print(train[['RoomService', 'Transported']].groupby(['RoomService'], as_index=False).mean())

print(result['FoodCourt'].mean())
train.loc[train['FoodCourt']<result['FoodCourt'].mean(),'FoodCourt'] = 0
train.loc[train['FoodCourt']>=result['FoodCourt'].mean() ,'FoodCourt'] = 1
train['FoodCourt'] = train['FoodCourt'].astype(int)

print(train[['FoodCourt', 'Transported']].groupby(['FoodCourt'], as_index=False).mean())

print(result['ShoppingMall'].mean())

train.loc[train['ShoppingMall']<result['ShoppingMall'].mean(),'ShoppingMall'] = 0
train.loc[train['ShoppingMall']>=result['ShoppingMall'].mean() ,'ShoppingMall'] = 1
train['ShoppingMall'] = train['ShoppingMall'].astype(int)

print(train[['ShoppingMall', 'Transported']].groupby(['ShoppingMall'], as_index=False).mean())


   CryoSleep  Transported
0      False     0.335042
1       True     0.817583
   Age  Transported
0    1     0.545275
1    2     0.473088
2    3     0.489407
218.3780262143408
   RoomService  Transported
0            0     0.577081
1            1     0.181931
441.8909791827294
   FoodCourt  Transported
0          0     0.509970
1          1     0.472468
170.77949113338474
   ShoppingMall  Transported
0             0     0.524253
1             1     0.404539


In [69]:

train['group'] = train.PassengerId.str.extract( r'(\d+)\_', expand=False)
train['number'] = train.PassengerId.str.extract( r'\_(\d+)', expand=False)

print(train['group'].unique())
print(train['number'].unique())

['0001' '0002' '0003' ... '9278' '9279' '9280']
['01' '02' '03' '04' '05' '06' '07' '08']


In [70]:
train['deck'] = train.Cabin.str.extract( '([A-Za-z]+)\/', expand=False)
train['num'] = train.Cabin.str.extract( r'(\d+)', expand=False)
train['side'] = train.Cabin.str.extract( '\/([A-Za-z]+)', expand=False)


print(train['deck'].unique())
print(train['num'].unique())
print(train['side'].unique())

['B' 'F' 'A' 'G' 'E' 'D' 'C' 'T']
['0' '1' '2' ... '1892' '1893' '1894']
['P' 'S']


In [152]:
train['Name'] = train.Name.str.extract( '(\ [A-Za-z]+)', expand=False)
print(train['Name'])

2213
